### ISSUE TITLE
Sidebar Form: required icons are blended to the form background

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Travel-Directors#111]
![image](https://cloud.githubusercontent.com/assets/17717843/14274553/a182a1d6-fb44-11e5-9e24-629634b4dbba.png)

**Comment by maehtitan** [comment]
enhance validation message to #ff4f4f

**Comment by dremensayson** [comment]
![image](https://cloud.githubusercontent.com/assets/17717843/14376715/c937c37c-fd9d-11e5-9ca2-f23fcde9f4fb.png)
