### ISSUE TITLE
Admin - Tours: Created a newly post item and assigning it to a specific subcategory, observe the first image it is placed under the Test Category but when it is being published the sub-category lines up with the Parent Category

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#26]
![image](https://cloud.githubusercontent.com/assets/13363508/14060471/cc2af21e-f39f-11e5-802d-e3ce400f1905.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14060476/135dcfa8-f3a0-11e5-8574-0c246687043d.png)

**Comment by judetitan** [comment]
Wordpress Bug in Category Heirarchy
