### ISSUE TITLE
404 / Error Page: We have a standard content for the page not found content, so is it okay to not use the standard and only based from the design given?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#4]
https://knowledgebase.titanweb.com.au/implementation/standard-pages/page-content-styling
![image](https://cloud.githubusercontent.com/assets/13363508/14041421/ab869814-f2ab-11e5-8a6b-32205e3adf17.png)

**Comment by judetitan** [comment]
as stated by Sir Berns we should just follow the design.
