### ISSUE TITLE
General: Dummy content added from docs to the site implemented makes the alphabet list turn to number list, 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#43]

**Comment by dremensayson** [comment]
change the alphabetical bullet from uppercase to lowercase

**Comment by dremensayson** [comment]
Fixed: bullet are now in lowercase

![image](https://cloud.githubusercontent.com/assets/17717843/14377212/3cdaf58a-fda1-11e5-9cc6-70ce83b67f16.png)
