### ISSUE TITLE
Blog: Post contents line of texts doesn't limit to 6 lines

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#44]
![image](https://cloud.githubusercontent.com/assets/13363508/14061060/779399ce-f3b1-11e5-8574-b19183023951.png)

**Comment by dremensayson** [comment]
inconsistent line limits, some blogs displayed 4 lines, 5 lines and other 6 lines. I notice that bulleted content is not displayed

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14377184/fe0bd3ce-fda0-11e5-8116-1de107cbd31a.png)
