### ISSUE TITLE
Tours Single - PDF Section: Repeater background layout isn't match from the design

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#46]
![image](https://cloud.githubusercontent.com/assets/13363508/14065953/cb2adfe8-f46f-11e5-88b8-ec25256818d1.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14065957/edc1de80-f46f-11e5-999a-f30b764a21d0.png)

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14377145/bb1e867e-fda0-11e5-8b2c-4d6943af7368.png)
