### ISSUE TITLE
Titan Options: Removing the shortcode will not completely removed the layout of the sidebar area

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#50]
![image](https://cloud.githubusercontent.com/assets/13363508/14061281/47e8bc80-f3b7-11e5-8fe1-133000e4f372.png)

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14377083/5908af8c-fda0-11e5-82b8-0315859880df.png)
