### ISSUE TITLE
Admin - Titan Theme Options: Incorrect login logo used including the link URL

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#55]
![image](https://cloud.githubusercontent.com/assets/13363508/14061347/3aff25de-f3b9-11e5-853f-ca8d4d34f3e7.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14061353/5e5009ea-f3b9-11e5-9301-0ecf2e358c49.png)

**Comment by dremensayson** [comment]
login logo is correct but the url link/tooltip is still titan digital

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14376937/71418ea8-fd9f-11e5-9a10-487c5cf15ccb.png)
