### ISSUE TITLE
Titan Theme Options - Login logo: Image ACF isn't required

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#56]
![image](https://cloud.githubusercontent.com/assets/13363508/14061363/8e35bde4-f3b9-11e5-89f9-379ae1afeae9.png)

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14377040/1e317f10-fda0-11e5-9d82-fb706aababe8.png)
