### ISSUE TITLE
Header Section: Incorrect font-family used in main menu 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#60]
![image](https://cloud.githubusercontent.com/assets/13363508/14065614/9bd721ea-f463-11e5-8997-e79ea1f5dd1b.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14065618/c04563f2-f463-11e5-9a33-a3fc9dc843a5.png)

**Comment by judetitan** [comment]
font size reduced to one pixel to fit to bootstrap grid. (Design Error: Menu on design doesn't fit on grid)
