### ISSUE TITLE
Footer Section: Separators are way too long compared to the design.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#63]
![image](https://cloud.githubusercontent.com/assets/13363508/14065647/b02ce156-f464-11e5-9dcd-59fd750d57f0.png)

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14376910/2c45aec4-fd9f-11e5-9a94-a4d6c8ad57cf.png)
