### ISSUE TITLE
Header Top Section - Ipad (portrait): Based from the given design 00-TRA-responsive.psd under Assets folder, header top implemented completely different from the design

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#86]
![image](https://cloud.githubusercontent.com/assets/13363508/14072513/d59525d6-f4f3-11e5-9e17-fa00930772e4.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14072515/d89884a8-f4f3-11e5-96b5-788a8aa15a57.png)

**Comment by dremensayson** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/17717843/14376888/fd0cf6e4-fd9e-11e5-8f72-ad6db8945bd6.png)
