### ISSUE TITLE
Header Top Section - General Mobile : Menus isn't implemented as burger menu 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#87]
Please apply fix in ipad landscape view
![image](https://cloud.githubusercontent.com/assets/13363508/14072561/4e9d8e32-f4f4-11e5-93c7-f0e8f6dd1e5b.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14072563/596231f6-f4f4-11e5-940b-bb35f98b735e.png)

**Comment by judetitan** [comment]
Plugin issue cant override default set-up from plugin
