### ISSUE TITLE
Banner Section - General Mobile: Based from the ipad portrait 768px design, logo and the menu section should fall under the banner section, currently they are all black.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#88]
![image](https://cloud.githubusercontent.com/assets/13363508/14072679/4b98c840-f4f5-11e5-8120-224dcd4d43aa.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14072788/25b9ca42-f4f6-11e5-971e-4ba03035c08c.png)

**Comment by judetitan** [comment]
hamburger menu of default bootstrap has set to fall at a certain width so it can't follow the mobile menu on the said design
