### ISSUE TITLE
Footer Section: Incorrect position of the footer layout

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Travel-Directors#98]
![image](https://cloud.githubusercontent.com/assets/13363508/14073378/1a75cfa0-f4fb-11e5-88f9-cc19e685c66a.png)
![image](https://cloud.githubusercontent.com/assets/13363508/14073392/31a80256-f4fb-11e5-94c0-8b70b6d0b4c4.png)

**Comment by judetitan** [comment]
Design Error: Grids for the images and license wouldn't fit on the set grid for bootstrap
